import test from "node:test";
import assert from "node:assert/strict";
import { POSTGRES_BOOTSTRAP_STATEMENTS, bootstrapPostgresSchema } from "../lib/postgres-bootstrap.js";
import { PostgresBackend, wrapSqliteDb, type PgQueryable } from "../lib/db-backend.js";
import { SignCliError } from "../lib/sign-error.js";
import { createDb, makeTempDb } from "./helpers.js";

test("bootstrapPostgresSchema runs every DDL statement against the pg client and reports the table set", async () => {
  const seen: string[] = [];
  const fakeClient: PgQueryable = {
    async query(text) {
      seen.push(text);
      return { rows: [], rowCount: 0 };
    },
  };
  const backend = new PostgresBackend(fakeClient);
  const report = await bootstrapPostgresSchema(backend);
  assert.equal(report.statementsRun, POSTGRES_BOOTSTRAP_STATEMENTS.length);
  assert.deepEqual(report.tables.sort(), [
    "approvals",
    "artifacts",
    "audit_events",
    "idempotency_keys",
    "requests",
    "signer_signing_states",
    "webhook_dedupe",
  ]);
  // Confirm every statement reached the client.
  assert.equal(seen.length, POSTGRES_BOOTSTRAP_STATEMENTS.length);
  // The append-only PL/pgSQL function is part of the bootstrap.
  assert.ok(seen.some((s) => s.includes("audit_events_append_only")));
  // Triggers reference that function.
  assert.ok(seen.some((s) => /CREATE TRIGGER audit_events_no_update/.test(s)));
  assert.ok(seen.some((s) => /CREATE TRIGGER audit_events_no_delete/.test(s)));
});

test("bootstrapPostgresSchema refuses to run against a SQLite backend", async () => {
  const { dbPath, cleanup } = makeTempDb();
  const db = createDb(dbPath);
  try {
    const backend = wrapSqliteDb(db);
    await assert.rejects(
      () => bootstrapPostgresSchema(backend),
      (err: unknown) => err instanceof SignCliError && err.code === "INVALID_ARGS",
    );
  } finally {
    db.close();
    cleanup();
  }
});

test("POSTGRES_BOOTSTRAP_STATEMENTS uses Postgres-flavor identity columns (no AUTOINCREMENT)", () => {
  const all = POSTGRES_BOOTSTRAP_STATEMENTS.join("\n");
  assert.ok(!/AUTOINCREMENT/.test(all), "Postgres bootstrap must not contain AUTOINCREMENT");
  assert.ok(/GENERATED BY DEFAULT AS IDENTITY/.test(all), "audit_events.id should use GENERATED IDENTITY");
  // No SQLite PRAGMAs.
  assert.ok(!/PRAGMA/.test(all), "Postgres bootstrap must not contain PRAGMAs");
});
