// Postgres-flavor port of the SQLite schema in src/lib/db.ts. Diffs from SQLite:
//
//  * INTEGER PRIMARY KEY AUTOINCREMENT  →  BIGINT GENERATED BY DEFAULT AS IDENTITY
//  * No PRAGMA — Postgres enforces FKs by default; WAL is irrelevant.
//  * `RAISE(ABORT, ...)` triggers replaced with PL/pgSQL trigger functions
//    that RAISE EXCEPTION.
//  * IF NOT EXISTS on every CREATE so the bootstrap is idempotent.
//
// `bootstrapPostgresSchema(backend)` runs this against a real PostgresBackend
// — the entry point for `sign db migrate-postgres`. It does NOT replicate the
// versioned migration history yet (those are SQLite-specific PRAGMAs); future
// work tracked in MIGRATION.md.

import type { DbBackend } from "./db-backend.js";
import { SignCliError } from "./sign-error.js";

export const POSTGRES_BOOTSTRAP_STATEMENTS: ReadonlyArray<string> = [
  `CREATE TABLE IF NOT EXISTS requests (
     id TEXT PRIMARY KEY,
     title TEXT NOT NULL,
     document_path TEXT NOT NULL,
     document_hash TEXT NOT NULL,
     status TEXT NOT NULL,
     provider TEXT,
     provider_request_id TEXT,
     provider_status TEXT,
     dropbox_signature_request_id TEXT,
     dropbox_status TEXT,
     signature_ids_json TEXT,
     signers_json TEXT NOT NULL,
     documents_json TEXT,
     fields_json TEXT,
     template_id TEXT,
     prefills_json TEXT,
     created_at TEXT NOT NULL,
     updated_at TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS approvals (
     id TEXT PRIMARY KEY,
     request_id TEXT NOT NULL REFERENCES requests(id),
     signer_name TEXT NOT NULL,
     signer_email TEXT NOT NULL,
     signer_order INTEGER NOT NULL,
     token_hash TEXT NOT NULL UNIQUE,
     token_hint TEXT NOT NULL,
     doc_hash TEXT NOT NULL,
     expires_at TEXT NOT NULL,
     used_at TEXT,
     approved_at TEXT,
     created_at TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS audit_events (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     request_id TEXT NOT NULL REFERENCES requests(id),
     event_type TEXT NOT NULL,
     payload_json TEXT NOT NULL,
     hash_prev TEXT,
     hash_self TEXT NOT NULL,
     hash_algo TEXT NOT NULL DEFAULT 'sha256',
     created_at TEXT NOT NULL
   )`,
  `ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS hash_algo TEXT NOT NULL DEFAULT 'sha256'`,
  `CREATE TABLE IF NOT EXISTS artifacts (
     id TEXT PRIMARY KEY,
     request_id TEXT NOT NULL REFERENCES requests(id),
     kind TEXT NOT NULL,
     path TEXT NOT NULL,
     content_hash TEXT NOT NULL,
     metadata_json TEXT NOT NULL,
     created_at TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS webhook_dedupe (
     provider TEXT NOT NULL,
     event_key TEXT NOT NULL,
     request_id TEXT,
     first_seen_at TEXT NOT NULL,
     PRIMARY KEY (provider, event_key)
   )`,
  `CREATE TABLE IF NOT EXISTS idempotency_keys (
     scope TEXT NOT NULL,
     key TEXT NOT NULL,
     request_id TEXT,
     response_json TEXT NOT NULL,
     created_at TEXT NOT NULL,
     PRIMARY KEY (scope, key)
   )`,
  `CREATE TABLE IF NOT EXISTS signer_signing_states (
     request_id TEXT NOT NULL REFERENCES requests(id),
     signer_email TEXT NOT NULL,
     signer_name TEXT,
     signed_at TEXT,
     declined_at TEXT,
     decline_reason TEXT,
     source TEXT NOT NULL,
     updated_at TEXT NOT NULL,
     PRIMARY KEY (request_id, signer_email)
   )`,
  // PL/pgSQL counterpart of the SQLite RAISE(ABORT, ...) triggers. Replaceable
  // function so re-running the bootstrap is idempotent.
  `CREATE OR REPLACE FUNCTION audit_events_append_only() RETURNS trigger
   LANGUAGE plpgsql AS $$
   BEGIN
     IF TG_OP = 'UPDATE' THEN
       RAISE EXCEPTION 'audit_events is append-only; UPDATE not permitted';
     ELSIF TG_OP = 'DELETE' THEN
       RAISE EXCEPTION 'audit_events is append-only; DELETE not permitted';
     END IF;
     RETURN NULL;
   END;
   $$`,
  `DROP TRIGGER IF EXISTS audit_events_no_update ON audit_events`,
  `CREATE TRIGGER audit_events_no_update
     BEFORE UPDATE ON audit_events
     FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()`,
  `DROP TRIGGER IF EXISTS audit_events_no_delete ON audit_events`,
  `CREATE TRIGGER audit_events_no_delete
     BEFORE DELETE ON audit_events
     FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()`,
];

export type PostgresBootstrapReport = {
  statementsRun: number;
  tables: string[];
};

export async function bootstrapPostgresSchema(backend: DbBackend): Promise<PostgresBootstrapReport> {
  if (backend.kind !== "postgres") {
    throw new SignCliError({
      code: "INVALID_ARGS",
      message: `bootstrapPostgresSchema requires a PostgresBackend; got kind="${backend.kind}".`,
    });
  }
  for (const stmt of POSTGRES_BOOTSTRAP_STATEMENTS) {
    await backend.execAsync(stmt);
  }
  return {
    statementsRun: POSTGRES_BOOTSTRAP_STATEMENTS.length,
    tables: [
      "requests",
      "approvals",
      "audit_events",
      "artifacts",
      "webhook_dedupe",
      "idempotency_keys",
      "signer_signing_states",
    ],
  };
}
