import type { ReceiptVerificationResult } from "./receipt-verify.js";

function escapeHtml(value: string): string {
  return value
    .replace(/&/gu, "&amp;")
    .replace(/</gu, "&lt;")
    .replace(/>/gu, "&gt;")
    .replace(/"/gu, "&quot;")
    .replace(/'/gu, "&#39;");
}

function statusBadge(ok: boolean, label: string): string {
  const bg = ok ? "#0a7c1f" : "#a91414";
  return `<span style="background:${bg};color:#fff;padding:2px 8px;border-radius:4px;font-weight:600;">${escapeHtml(label)}</span>`;
}

export function renderReceiptVerificationHtml(result: ReceiptVerificationResult): string {
  const overall = statusBadge(result.ok, result.ok ? "VERIFIED" : "FAILED");
  const manifestLine = `<li>Manifest signature: ${statusBadge(result.manifestVerified, result.manifestVerified ? "verified" : "INVALID")} ` +
    `<code>sha256=${escapeHtml(result.manifestSha256)}</code></li>`;
  const subjectLine = result.signerSubject
    ? `<li>Signer cert subject: <code>${escapeHtml(result.signerSubject)}</code></li>`
    : "";
  const filesRows = result.files
    .map((f) => `<tr><td><code>${escapeHtml(f.name)}</code></td><td>${statusBadge(f.ok, f.ok ? "match" : "MISMATCH")}</td><td><code>${escapeHtml(f.expected)}</code></td><td><code>${escapeHtml(f.actual)}</code></td></tr>`)
    .join("\n");
  const chainLine = result.chain
    ? `<li>Audit chain: ${statusBadge(result.chain.ok, result.chain.ok ? `${result.chain.events} events linked` : "broken")}` +
      (result.chain.break
        ? ` <code>${escapeHtml(result.chain.break.kind)} at event ${result.chain.break.eventId}</code>`
        : "") +
      `</li>`
    : `<li>Audit chain: <em>not present</em></li>`;
  const errorList = result.errors.length === 0
    ? ""
    : `<h3>Errors</h3><ul>${result.errors.map((e) => `<li><code>${escapeHtml(e)}</code></li>`).join("")}</ul>`;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Sign CLI receipt verification</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; max-width: 760px; margin: 2em auto; padding: 0 1em; color: #222; line-height: 1.45; }
    h1 { margin-top: 0; }
    code { background: #f3f3f3; padding: 1px 4px; border-radius: 3px; font-size: 0.92em; }
    table { border-collapse: collapse; width: 100%; margin-top: 0.5em; }
    th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; font-size: 0.9em; vertical-align: top; }
    th { background: #f7f7f7; }
    ul { padding-left: 1.2em; }
    .meta { color: #666; font-size: 0.85em; }
  </style>
</head>
<body>
  <h1>Sign CLI receipt verification ${overall}</h1>
  <p class="meta">Bundle: <code>${escapeHtml(result.bundleDir)}</code></p>
  <ul>
    ${manifestLine}
    ${subjectLine}
    ${chainLine}
  </ul>
  <h3>Files</h3>
  <table>
    <thead><tr><th>name</th><th>status</th><th>expected sha256</th><th>actual sha256</th></tr></thead>
    <tbody>
      ${filesRows || `<tr><td colspan="4"><em>no files in manifest</em></td></tr>`}
    </tbody>
  </table>
  ${errorList}
  <p class="meta">Generated by <code>sign request verify-receipt --html</code>. Verification is reproducible: re-run the command to regenerate this report.</p>
</body>
</html>
`;
}
